"""
Reptile data for the typing trainer game.
Each reptile has a common name, scientific name, fun fact, and a Wikimedia Commons filename.
All images are from Wikimedia Commons and are freely licensed (CC-BY, CC-BY-SA, or Public Domain).
Images are chosen to be child-appropriate (no feeding/predation scenes).

The `image_file` field is the Wikimedia Commons filename (without "File:" prefix).
The image_manager module resolves these to download URLs via the Wikimedia API.
"""

REPTILES = [
    {
        "common_name": 'Green Iguana',
        "scientific_name": 'Iguana iguana',
        "fun_fact": 'Green iguanas can grow up to 6 feet long including their tail!',
        "image_file": 'Iguana_iguana_Portoviejo_02.jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 4.0',
    },
    {
        "common_name": 'Leopard Gecko',
        "scientific_name": 'Eublepharis macularius',
        "fun_fact": 'Leopard geckos store fat in their tails for energy!',
        "image_file": 'Eublepharis macularius 2009 G6.jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 3.0',
    },
    {
        "common_name": 'Bearded Dragon',
        "scientific_name": 'Pogona vitticeps',
        "fun_fact": 'Bearded dragons wave their arms to say hello to each other!',
        "image_file": 'Bartagame_fcm.jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 3.0',
    },
    {
        "common_name": 'Red-Eared Slider',
        "scientific_name": 'Trachemys scripta elegans',
        "fun_fact": 'Red-eared sliders can live for over 30 years!',
        "image_file": 'Red-eared slider (Trachemys scripta elegans).jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 4.0',
    },
    {
        "common_name": 'Chameleon',
        "scientific_name": 'Chamaeleo calyptratus',
        "fun_fact": 'Chameleons can move their eyes independently in two different directions!',
        "image_file": 'Yemen_Chameleon_(cropped).jpg',
        "image_credit": 'Wikimedia Commons, CC BY 2.0',
    },
    {
        "common_name": 'Corn Snake',
        "scientific_name": 'Pantherophis guttatus',
        "fun_fact": 'Corn snakes are excellent climbers and can scale trees and walls!',
        "image_file": 'Kornnatter.jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 3.0',
    },
    {
        "common_name": 'Blue-Tongued Skink',
        "scientific_name": 'Tiliqua scincoides',
        "fun_fact": 'Blue-tongued skinks stick out their bright blue tongue to scare away predators!',
        "image_file": 'Tiliqua scincoides (White, 1790).jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 3.0',
    },
    {
        "common_name": 'Green Sea Turtle',
        "scientific_name": 'Chelonia mydas',
        "fun_fact": 'Green sea turtles can hold their breath for up to 5 hours while sleeping!',
        "image_file": 'Green sea turtle (Chelonia mydas) Moorea.jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 4.0',
    },
    {
        "common_name": 'Komodo Dragon',
        "scientific_name": 'Varanus komodoensis',
        "fun_fact": 'Komodo dragons are the largest living lizards and can run up to 13 mph!',
        "image_file": 'Komodo_dragon_with_tongue.jpg',
        "image_credit": 'Wikimedia Commons, Public Domain',
    },
    {
        "common_name": 'Ball Python',
        "scientific_name": 'Python regius',
        "fun_fact": 'Ball pythons curl into a tight ball when they feel scared — that is how they got their name!',
        "image_file": 'Ball_python_lucy.JPG',
        "image_credit": 'Wikimedia Commons, CC BY-SA 3.0',
    },
    {
        "common_name": 'Gila Monster',
        "scientific_name": 'Heloderma suspectum',
        "fun_fact": 'The Gila monster is one of only a few venomous lizards in the world!',
        "image_file": 'Gila_monster_(Heloderma_suspectum).jpg',
        "image_credit": 'Wikimedia Commons, Public Domain',
    },
    {
        "common_name": 'Tokay Gecko',
        "scientific_name": 'Gekko gecko',
        "fun_fact": 'Tokay geckos make a loud to-kay call — that is how they got their name!',
        "image_file": 'Tokay_Gecko.jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 3.0',
    },
    {
        "common_name": 'Saltwater Crocodile',
        "scientific_name": 'Crocodylus porosus',
        "fun_fact": 'Saltwater crocodiles are the largest living reptiles and can weigh over 2,000 pounds!',
        "image_file": 'Saltwater Crocodile (Crocodylus porosus) (10106331165).jpg',
        "image_credit": 'Wikimedia Commons, CC BY 2.0',
    },
    {
        "common_name": 'Frilled Lizard',
        "scientific_name": 'Chlamydosaurus kingii',
        "fun_fact": 'The frilled lizard opens a large frill around its neck to look bigger and scare off threats!',
        "image_file": 'Chlamydosaurus_kingii.jpg',
        "image_credit": 'Wikimedia Commons, CC BY-SA 2.5',
    },
    {
        "common_name": 'Painted Turtle',
        "scientific_name": 'Chrysemys picta',
        "fun_fact": 'Painted turtles love to bask in the sun and can often be seen lined up on logs!',
        "image_file": 'Painted_turtle.jpg',
        "image_credit": 'Wikimedia Commons, Public Domain',
    },
    {
        "common_name": 'American Alligator',
        "scientific_name": 'Alligator mississippiensis',
        "fun_fact": 'American alligators can live up to 50 years in the wild!',
        "image_file": 'Alligator mississippiensis 113744549.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Eastern Box Turtle',
        "scientific_name": 'Terrapene carolina',
        "fun_fact": 'Eastern box turtles can completely close their shell like a box!',
        "image_file": 'Florida Box Turtle Digon3.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'King Cobra',
        "scientific_name": 'Ophiophagus hannah',
        "fun_fact": 'King cobras can grow up to 18 feet, making them the longest venomous snake!',
        "image_file": 'King cobra (Ophiophagus hannah) Bach Ma 2.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Green Anole',
        "scientific_name": 'Anolis carolinensis',
        "fun_fact": 'Green anoles can change color from bright green to brown!',
        "image_file": 'Anole Lizard Hilo Hawaii edit.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Nile Crocodile',
        "scientific_name": 'Crocodylus niloticus',
        "fun_fact": 'Nile crocodiles can hold their breath underwater for up to 2 hours!',
        "image_file": 'Cocodrilo del Nilo (Crocodylus niloticus), parque nacional de Chobe, Botsuana, 2018-07-28, DD 86.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Leatherback Sea Turtle',
        "scientific_name": 'Dermochelys coriacea',
        "fun_fact": 'Leatherback sea turtles are the largest turtles in the world!',
        "image_file": 'Taxidermied Leatherback sea turtle (Dermochelys coriacea), Lee Kong Chian Natural History Museum (104136).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Garter Snake',
        "scientific_name": 'Thamnophis sirtalis',
        "fun_fact": 'Garter snakes are one of the most common snakes in North America!',
        "image_file": 'California Red-Sided Garter Snake (Thamnophis sirtalis infernalis).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Thorny Devil',
        "scientific_name": 'Moloch horridus',
        "fun_fact": 'Thorny devils can drink water through their skin!',
        "image_file": 'Thornydevil.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Eastern Diamondback Rattlesnake',
        "scientific_name": 'Crotalus adamanteus',
        "fun_fact": 'Eastern diamondback rattlesnakes add a new rattle segment each time they shed!',
        "image_file": 'Crotalus adamanteus 153487454.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Tuatara',
        "scientific_name": 'Sphenodon punctatus',
        "fun_fact": 'Tuataras have a third eye on top of their head that senses light!',
        "image_file": 'Sphenodon punctatus 106371236.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Spectacled Caiman',
        "scientific_name": 'Caiman crocodilus',
        "fun_fact": 'Spectacled caimans get their name from the ridge between their eyes!',
        "image_file": 'Spectacled caiman in Costa Rica 01.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Panther Chameleon',
        "scientific_name": 'Furcifer pardalis',
        "fun_fact": 'Panther chameleons can shoot their tongue out faster than a jet plane takes off!',
        "image_file": 'Panther chameleon (Furcifer pardalis) male Nosy Be.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Chinese Water Dragon',
        "scientific_name": 'Physignathus cocincinus',
        "fun_fact": 'Chinese water dragons can run on their hind legs across water!',
        "image_file": 'Physignathus cocincinus 112231456.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Nile Monitor',
        "scientific_name": 'Varanus niloticus',
        "fun_fact": 'Nile monitors are excellent swimmers and can stay underwater for over an hour!',
        "image_file": 'Nile monitor lizard (Varanus niloticus) head.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Carpet Python',
        "scientific_name": 'Morelia spilota',
        "fun_fact": 'Carpet pythons can sense body heat to find their prey in the dark!',
        "image_file": 'Morelia spilota head.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Alligator Snapping Turtle',
        "scientific_name": 'Macrochelys temminckii',
        "fun_fact": 'Alligator snapping turtles use a worm-shaped lure on their tongue to attract fish!',
        "image_file": 'Alligator Snapping Turtle (Macrochelys temminckii) (35856633000).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Collared Lizard',
        "scientific_name": 'Crotaphytus collaris',
        "fun_fact": 'Collared lizards can run on just their two back legs!',
        "image_file": 'Crotaphytus collaris - Wilhelma 01.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Indigo Snake',
        "scientific_name": 'Drymarchon couperi',
        "fun_fact": 'Indigo snakes are the longest native snake species in the United States!',
        "image_file": 'Eastern indigo snake (Drymarchon couperi).png',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Hawksbill Sea Turtle',
        "scientific_name": 'Eretmochelys imbricata',
        "fun_fact": 'Hawksbill sea turtles have a beautiful shell pattern that is unique to each turtle!',
        "image_file": 'Tortuga carey (Eretmochelys imbricata), parque nacional Ras Muhammad, Egipto, 2022-03-28, DD 56.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Jackson Chameleon',
        "scientific_name": 'Trioceros jacksonii',
        "fun_fact": 'Jackson chameleons have three horns on their head like a tiny triceratops!',
        "image_file": 'Trioceros jacksonii 114285602.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Pygmy Chameleon',
        "scientific_name": 'Rhampholeon',
        "fun_fact": 'Some pygmy chameleons are so small they can sit on your fingertip!',
        "image_file": 'Rhampholeon temporalis.png',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Galápagos Tortoise',
        "scientific_name": 'Chelonoidis nigra',
        "fun_fact": 'Galápagos tortoises can live for over 150 years!',
        "image_file": 'Galápagos tortoise Santa Cruz.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Aldabra Giant Tortoise',
        "scientific_name": 'Aldabrachelys gigantea',
        "fun_fact": 'Aldabra giant tortoises can weigh over 500 pounds!',
        "image_file": 'Aldabra Giant Tortoise Geochelone gigantea edit1.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Desert Tortoise',
        "scientific_name": 'Gopherus agassizii',
        "fun_fact": 'Desert tortoises spend up to 95 percent of their lives in underground burrows!',
        "image_file": 'Gopherus agassizii.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Russian Tortoise',
        "scientific_name": 'Testudo horsfieldii',
        "fun_fact": 'Russian tortoises are great diggers and love to burrow underground!',
        "image_file": 'Testudo horsfieldii; Baikonur 001.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Sulcata Tortoise',
        "scientific_name": 'Centrochelys sulcata',
        "fun_fact": 'Sulcata tortoises are the third largest tortoise species in the world!',
        "image_file": 'African spurred tortoise (Centrochelys sulcata), Gembira Loka Zoo, 2015-03-15.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Loggerhead Sea Turtle',
        "scientific_name": 'Caretta caretta',
        "fun_fact": 'Loggerhead sea turtles have extra-large heads and powerful jaws!',
        "image_file": 'Parque Nacional Marinho de Fernando de Noronha - João Paulo Marques DAndretta 12.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Mata Mata Turtle',
        "scientific_name": 'Chelus fimbriata',
        "fun_fact": 'Mata mata turtles look like a pile of leaves to hide from predators!',
        "image_file": '2009 Chelus fimbriatus.JPG',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Softshell Turtle',
        "scientific_name": 'Apalone spinifera',
        "fun_fact": 'Softshell turtles have a flexible leathery shell instead of a hard one!',
        "image_file": 'Spiny softshell turtle (Apalone spinifera).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Western Fence Lizard',
        "scientific_name": 'Sceloporus occidentalis',
        "fun_fact": 'Western fence lizards do push-ups to show off to other lizards!',
        "image_file": 'Sceloporus occidentalis, Sacramento County, California.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Sand Lizard',
        "scientific_name": 'Lacerta agilis',
        "fun_fact": 'Male sand lizards turn bright green during mating season!',
        "image_file": 'Lacerta agilis male 2011 G2.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Common Wall Lizard',
        "scientific_name": 'Podarcis muralis',
        "fun_fact": 'Wall lizards can climb straight up walls and even hang upside down!',
        "image_file": '20210612 Podarcis muralis 03.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Five-Lined Skink',
        "scientific_name": 'Plestiodon fasciatus',
        "fun_fact": 'Baby five-lined skinks have bright blue tails that distract predators!',
        "image_file": 'DO - Common Five-lined Skink (Plestiodon fasciatus) (4073328823).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Crested Gecko',
        "scientific_name": 'Correlophus ciliatus',
        "fun_fact": 'Crested geckos were thought to be extinct until they were rediscovered in 1994!',
        "image_file": 'Gekkoninae Rhacodactylus ciliatus tete.png',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Gargoyle Gecko',
        "scientific_name": 'Rhacodactylus auriculatus',
        "fun_fact": 'Gargoyle geckos get their name from the bumps on their head that look like horns!',
        "image_file": 'Rhacodactylus auriculatus.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Day Gecko',
        "scientific_name": 'Phelsuma grandis',
        "fun_fact": 'Day geckos have special toe pads that let them climb smooth glass!',
        "image_file": 'Phelsuma grandis, Stuttgart Zoological Garden.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Flying Gecko',
        "scientific_name": 'Ptychozoon kuhli',
        "fun_fact": 'Flying geckos have flaps of skin that let them glide between trees!',
        "image_file": 'Ptychozoon kuhli.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Leaf-Tailed Gecko',
        "scientific_name": 'Uroplatus phantasticus',
        "fun_fact": 'Leaf-tailed geckos look exactly like a dead leaf to hide from predators!',
        "image_file": 'Satanic leaf-tailed gecko (Uroplatus phantasticus) Ranomafana composite.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Giant Day Gecko',
        "scientific_name": 'Phelsuma madagascariensis',
        "fun_fact": 'Giant day geckos lick nectar from flowers like tiny lizard hummingbirds!',
        "image_file": 'Phelsuma grandis, Mauritius.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'African Fat-Tailed Gecko',
        "scientific_name": 'Hemitheconyx caudicinctus',
        "fun_fact": 'African fat-tailed geckos store food in their chubby tails for hard times!',
        "image_file": 'Hemitheconyx caudicinctus.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Green Tree Python',
        "scientific_name": 'Morelia viridis',
        "fun_fact": 'Green tree pythons change color from yellow or red to green as they grow up!',
        "image_file": 'Green Tree Python 0A2A0428.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Emerald Tree Boa',
        "scientific_name": 'Corallus caninus',
        "fun_fact": 'Emerald tree boas have heat-sensing pits along their lips!',
        "image_file": 'Corallus caninus.JPG',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Boa Constrictor',
        "scientific_name": 'Boa constrictor',
        "fun_fact": 'Boa constrictors give birth to live babies instead of laying eggs!',
        "image_file": 'Red-tailed boa (Boa constrictor constrictor) Rio Napo.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Reticulated Python',
        "scientific_name": 'Malayopython reticulatus',
        "fun_fact": 'Reticulated pythons are the longest snakes in the world!',
        "image_file": 'Malayopython reticulatus, Reticulated python - Kaeng Krachan District, Phetchaburi Province (47924282891).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Kingsnake',
        "scientific_name": 'Lampropeltis getula',
        "fun_fact": 'Kingsnakes are immune to the venom of other snakes!',
        "image_file": 'Lampropeltis getula getula.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Milk Snake',
        "scientific_name": 'Lampropeltis triangulum',
        "fun_fact": 'Milk snakes copy the colors of venomous coral snakes to scare predators!',
        "image_file": 'Eastern Milk Snake (Lampropeltis triangulum triangulum) (40682943834).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Hognose Snake',
        "scientific_name": 'Heterodon nasicus',
        "fun_fact": 'Hognose snakes play dead when they feel threatened, rolling onto their backs!',
        "image_file": 'Heterodon nasicus.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Rat Snake',
        "scientific_name": 'Pantherophis obsoletus',
        "fun_fact": 'Rat snakes are amazing climbers and can go straight up a tree trunk!',
        "image_file": 'Black Rat Snake (Pantherophis obsoletus).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Rough Green Snake',
        "scientific_name": 'Opheodrys aestivus',
        "fun_fact": 'Rough green snakes are so well camouflaged they look like vines!',
        "image_file": 'Opheodrys aestivus on rocks.JPG',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Woma Python',
        "scientific_name": 'Aspidites ramsayi',
        "fun_fact": 'Woma pythons use their head to pin prey against burrow walls!',
        "image_file": 'Woma 01 Pengo.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Black Mamba',
        "scientific_name": 'Dendroaspis polylepis',
        "fun_fact": 'Black mambas are the fastest snakes in the world at 12 miles per hour!',
        "image_file": 'Makalali Game Reserve (ZA), Schlange -- 2024 -- 1091.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Gaboon Viper',
        "scientific_name": 'Bitis gabonica',
        "fun_fact": 'Gaboon vipers have the longest fangs of any snake at up to 2 inches!',
        "image_file": 'Gabunviper Bitis gabonica-7848.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Sidewinder',
        "scientific_name": 'Crotalus cerastes',
        "fun_fact": 'Sidewinders move in a unique sideways motion to travel across hot sand!',
        "image_file": 'Crotalus cerastes mesquite springs CA-2.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Cottonmouth',
        "scientific_name": 'Agkistrodon piscivorus',
        "fun_fact": 'Cottonmouths get their name from the white inside of their mouth!',
        "image_file": 'Agkistrodon piscivorus 5.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Copperhead',
        "scientific_name": 'Agkistrodon contortrix',
        "fun_fact": 'Baby copperheads have a bright yellow tail tip they use to lure prey!',
        "image_file": 'Agkistrodon contortrix - Nantes.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Gharial',
        "scientific_name": 'Gavialis gangeticus',
        "fun_fact": 'Gharials have a long thin snout that is perfectly shaped for catching fish!',
        "image_file": 'Gharial (Gavialis gangeticus) female and juvenile.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Dwarf Crocodile',
        "scientific_name": 'Osteolaemus tetraspis',
        "fun_fact": 'Dwarf crocodiles are the smallest crocodile species, only about 5 feet long!',
        "image_file": 'Osteolaemus tetraspis - Karlsruhe Zoo 01.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Mugger Crocodile',
        "scientific_name": 'Crocodylus palustris',
        "fun_fact": 'Mugger crocodiles sometimes balance sticks on their nose to attract nest-building birds!',
        "image_file": 'Mugger crocodile (Crocodylus palustris) Gal Oya.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Marine Iguana',
        "scientific_name": 'Amblyrhynchus cristatus',
        "fun_fact": 'Marine iguanas are the only lizards that swim in the ocean!',
        "image_file": 'Iguana marina (Amblyrhynchus cristatus), Las Bachas, isla Santa Cruz, islas Galápagos, Ecuador, 2015-07-23, DD 23.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Rhinoceros Iguana',
        "scientific_name": 'Cyclura cornuta',
        "fun_fact": 'Rhinoceros iguanas have small horn-like bumps on their nose!',
        "image_file": 'Cyclura cornuta - Reptilium Landau.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Fiji Banded Iguana',
        "scientific_name": 'Brachylophus bulabula',
        "fun_fact": 'Fiji banded iguanas can change their color to blend in with leaves!',
        "image_file": 'Brachylophus bulabula.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Spiny-Tailed Iguana',
        "scientific_name": 'Ctenosaura similis',
        "fun_fact": 'Spiny-tailed iguanas are the fastest lizards, running up to 21 miles per hour!',
        "image_file": 'CtenosauraSimilis.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Savannah Monitor',
        "scientific_name": 'Varanus exanthematicus',
        "fun_fact": 'Savannah monitors have forked tongues like snakes to smell their surroundings!',
        "image_file": 'Varanus exanthematicus in the wild.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Asian Water Monitor',
        "scientific_name": 'Varanus salvator',
        "fun_fact": 'Asian water monitors can grow up to 6 feet long and love to swim!',
        "image_file": 'Closeup shot of Water monitor lizard, Varanus salvator from Diamond Harbour, WB, In 03.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Crocodile Monitor',
        "scientific_name": 'Varanus salvadorii',
        "fun_fact": 'Crocodile monitors have the longest tail of any lizard!',
        "image_file": 'Papuawaran Varanus salvadorii-7843.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Tegu',
        "scientific_name": 'Salvator merianae',
        "fun_fact": 'Tegus are one of the most intelligent lizard species and can be trained!',
        "image_file": 'Argentine black and white tegu (Salvator merianae) male Vicente Lopez.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Caiman Lizard',
        "scientific_name": 'Dracaena guianensis',
        "fun_fact": 'Caiman lizards have powerful jaws made for crushing snail shells!',
        "image_file": 'Dracaena guianensis (3).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Basilisk Lizard',
        "scientific_name": 'Basiliscus basiliscus',
        "fun_fact": 'Basilisk lizards can run across water, earning them the name Jesus Christ lizard!',
        "image_file": 'Common basilisk in Costa Rica 02.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Armadillo Lizard',
        "scientific_name": 'Ouroborus cataphractus',
        "fun_fact": 'Armadillo lizards bite their own tail and curl into a ball for protection!',
        "image_file": 'Ouroborus cataphractus 29188261.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Draco Lizard',
        "scientific_name": 'Draco volans',
        "fun_fact": 'Draco lizards have wing-like flaps that let them glide up to 25 feet!',
        "image_file": 'Draco volans 01.JPG',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Water Dragon',
        "scientific_name": 'Intellagama lesueurii',
        "fun_fact": 'Australian water dragons can hold their breath for up to 90 minutes!',
        "image_file": 'Eastern Water Dragon Clontarf.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Sailfin Lizard',
        "scientific_name": 'Hydrosaurus pustulatus',
        "fun_fact": 'Sailfin lizards have a large fin on their tail to help them swim!',
        "image_file": 'Hydrosaurus pustulatus Tropicario 1.JPG',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Uromastyx',
        "scientific_name": 'Uromastyx aegyptia',
        "fun_fact": 'Uromastyx lizards use their spiky tails like a club for defense!',
        "image_file": 'Egyptian.spiny.tail.lizard.arp.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Slow Worm',
        "scientific_name": 'Anguis fragilis',
        "fun_fact": 'Slow worms look like snakes but are actually legless lizards!',
        "image_file": 'Common slowworm (Anguis fragilis).jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Glass Lizard',
        "scientific_name": 'Ophisaurus ventralis',
        "fun_fact": 'Glass lizards can break off their tails, which shatter like glass!',
        "image_file": 'Eastern Glass Lizard.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Horned Lizard',
        "scientific_name": 'Phrynosoma cornutum',
        "fun_fact": 'Horned lizards can squirt blood from their eyes to scare predators!',
        "image_file": 'Phrynosoma cornutum 293505046.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Chuckwalla',
        "scientific_name": 'Sauromalus ater',
        "fun_fact": 'Chuckwallas puff up their bodies to wedge themselves into rock cracks!',
        "image_file": 'Sauromalus ater Phoenix.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Plumed Basilisk',
        "scientific_name": 'Basiliscus plumifrons',
        "fun_fact": 'Plumed basilisks have a beautiful bright green crest on their head!',
        "image_file": 'Plumedbasiliskcele4 edit.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Radiated Tortoise',
        "scientific_name": 'Astrochelys radiata',
        "fun_fact": 'Radiated tortoises have beautiful star-shaped patterns on their shells!',
        "image_file": 'Radiated tortoise (Astrochelys radiata) Tsimanampetsotsa.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Pancake Tortoise',
        "scientific_name": 'Malacochersus tornieri',
        "fun_fact": 'Pancake tortoises have a flat flexible shell so they can squeeze into rock crevices!',
        "image_file": 'Malacochersus tornieri - Buffalo Zoo.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Speckled Kingsnake',
        "scientific_name": 'Lampropeltis holbrooki',
        "fun_fact": 'Speckled kingsnakes have beautiful yellow dots all over their black body!',
        "image_file": 'Gefleckte Kettennatter (Lampropeltis holbrooki), Abwehrhaltung.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Rosy Boa',
        "scientific_name": 'Lichanura trivirgata',
        "fun_fact": 'Rosy boas are one of only two boa species found in the United States!',
        "image_file": 'C trivirgata saslowi 1.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Rainbow Boa',
        "scientific_name": 'Epicrates cenchria',
        "fun_fact": 'Rainbow boas have tiny ridges on their scales that create a rainbow shimmer!',
        "image_file": 'Epicrates cenchria 158446770.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Snapping Turtle',
        "scientific_name": 'Chelydra serpentina',
        "fun_fact": 'Snapping turtles have one of the strongest bites of any animal!',
        "image_file": 'Chelydra serpentina 2017 G1.jpg',
        "image_credit": 'Wikimedia Commons',
    },
    {
        "common_name": 'Map Turtle',
        "scientific_name": 'Graptemys geographica',
        "fun_fact": 'Map turtles have patterns on their shells that look like contour lines on a map!',
        "image_file": 'Northern Map Turtle.jpg',
        "image_credit": 'Wikimedia Commons',
    },
]
