"""
Sea creature data for the typing trainer game.
Each sea creature has a common name, scientific name, fun fact, and a Wikimedia Commons filename.
All images are from Wikimedia Commons and are freely licensed (CC-BY, CC-BY-SA, or Public Domain).
Images are chosen to be child-appropriate.

The `image_file` field is the Wikimedia Commons filename (without "File:" prefix).
The image_manager module resolves these to download URLs via the Wikimedia API.
"""

SEA_CREATURES = [
    {
        "common_name": "Clownfish",
        "scientific_name": "Amphiprion ocellaris",
        "fun_fact": "Clownfish live inside stinging sea anemones that protect them from predators!",
        "image_file": "Amphiprion ocellaris (Clown anemonefish) in Heteractis magnifica (Sea anemone).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Blue Tang",
        "scientific_name": "Paracanthurus hepatus",
        "fun_fact": "Blue tangs can make themselves semi-transparent to hide from predators!",
        "image_file": "Paletten-Doktorfisch Paracanthurus hepatus.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Sea Otter",
        "scientific_name": "Enhydra lutris",
        "fun_fact": "Sea otters hold hands while sleeping so they don't drift apart!",
        "image_file": "Sea otter cropped.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Bottlenose Dolphin",
        "scientific_name": "Tursiops truncatus",
        "fun_fact": "Bottlenose dolphins can recognize themselves in a mirror!",
        "image_file": "Tursiops truncatus 01.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Humpback Whale",
        "scientific_name": "Megaptera novaeangliae",
        "fun_fact": "Humpback whales sing complex songs that can be heard hundreds of miles away!",
        "image_file": "Humpback stellwagen edit.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Seahorse",
        "scientific_name": "Hippocampus kuda",
        "fun_fact": "Male seahorses are the ones who carry and give birth to babies!",
        "image_file": "Hippocampus kuda (Estuary seahorse).jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Moon Jellyfish",
        "scientific_name": "Aurelia aurita",
        "fun_fact": "Moon jellyfish have no brain, heart, or blood!",
        "image_file": "Moon jellyfish at Gota Sagher.JPG",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Giant Pacific Octopus",
        "scientific_name": "Enteroctopus dofleini",
        "fun_fact": "Giant Pacific octopuses have three hearts and blue blood!",
        "image_file": "Enteroctopus dofleini.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Manta Ray",
        "scientific_name": "Mobula birostris",
        "fun_fact": "Manta rays have the largest brains of any fish!",
        "image_file": "Manta birostris-Thailand4.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Great White Shark",
        "scientific_name": "Carcharodon carcharias",
        "fun_fact": "Great white sharks can detect a single drop of blood in 25 gallons of water!",
        "image_file": "White shark.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Whale Shark",
        "scientific_name": "Rhincodon typus",
        "fun_fact": "Whale sharks are the biggest fish in the world but only eat tiny plankton!",
        "image_file": "Rhincodon typus, Georgia Aquarium.jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Emperor Penguin",
        "scientific_name": "Aptenodytes forsteri",
        "fun_fact": "Emperor penguins can dive deeper than 1,800 feet underwater!",
        "image_file": "Aptenodytes forsteri -Snow Hill Island, Antarctica -adults and juvenile-8.jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Manatee",
        "scientific_name": "Trichechus manatus",
        "fun_fact": "Manatees are sometimes called sea cows because they graze on underwater grass!",
        "image_file": "Manatee with calf.PD - colourass.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Narwhal",
        "scientific_name": "Monodon monoceros",
        "fun_fact": "A narwhal's tusk is actually a giant tooth that can grow up to 10 feet long!",
        "image_file": "Narwhal (Monodon monoceros).jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Blue Whale",
        "scientific_name": "Balaenoptera musculus",
        "fun_fact": "Blue whales are the largest animals to have ever lived on Earth!",
        "image_file": "Anim1754 - Flickr - NOAA Photo Library.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Sea Turtle",
        "scientific_name": "Chelonia mydas",
        "fun_fact": "Sea turtles can hold their breath for up to five hours while sleeping!",
        "image_file": "Green sea turtle (Chelonia mydas) Moorea.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Hammerhead Shark",
        "scientific_name": "Sphyrna mokarran",
        "fun_fact": "Hammerhead sharks have 360-degree vision thanks to their wide-set eyes!",
        "image_file": "Hammerhead shark, Cocos Island, Costa Rica.jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Lionfish",
        "scientific_name": "Pterois volitans",
        "fun_fact": "Lionfish have venomous spines but are not dangerous to humans if left alone!",
        "image_file": "Red lionfish near Gilli Banta Island.JPG",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Starfish",
        "scientific_name": "Asterias rubens",
        "fun_fact": "Starfish can regrow a lost arm, and some can regrow their entire body from one arm!",
        "image_file": "Asterias rubens.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Beluga Whale",
        "scientific_name": "Delphinapterus leucas",
        "fun_fact": "Beluga whales are called canaries of the sea because they make so many sounds!",
        "image_file": "Beluga premier.gov.ru-2.jpeg",
        "image_credit": "Wikimedia Commons, CC BY 4.0",
    },
    {
        "common_name": "Pufferfish",
        "scientific_name": "Tetraodon lineatus",
        "fun_fact": "Pufferfish inflate themselves like a balloon to scare away predators!",
        "image_file": "Tetraodon lineatus.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Moray Eel",
        "scientific_name": "Gymnothorax javanicus",
        "fun_fact": "Moray eels have a second set of jaws inside their throat to pull in food!",
        "image_file": "Giant moray (Gymnothorax javanicus).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Orca",
        "scientific_name": "Orcinus orca",
        "fun_fact": "Orcas are actually the largest members of the dolphin family!",
        "image_file": "Killerwhales jumping.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Cuttlefish",
        "scientific_name": "Sepia officinalis",
        "fun_fact": "Cuttlefish can change color and texture in the blink of an eye!",
        "image_file": "Sepia officinalis Cuttlefish striridge.jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Hermit Crab",
        "scientific_name": "Pagurus bernhardus",
        "fun_fact": "Hermit crabs swap shells with each other in an organized line from biggest to smallest!",
        "image_file": "Pagurus bernhardus (Einsiedlerkrebs).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Green Moray Eel",
        "scientific_name": "Gymnothorax funebris",
        "fun_fact": "Green moray eels are not really green — they have yellow skin covered in blue mucus!",
        "image_file": "Green Moray Eel Gymnothorax funebris.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Sea Dragon",
        "scientific_name": "Phycodurus eques",
        "fun_fact": "Leafy sea dragons have leaf-shaped body parts that make them look like floating seaweed!",
        "image_file": "Phycodurus eques.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Portuguese Man-of-War",
        "scientific_name": "Physalia physalis",
        "fun_fact": "The Portuguese man-of-war is not one animal — it is a colony of tiny organisms working together!",
        "image_file": "Portuguese Man-O-War (Physalia physalis).jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Walrus",
        "scientific_name": "Odobenus rosmarus",
        "fun_fact": "Walrus tusks can grow up to 3 feet long and they use them to haul out of the water!",
        "image_file": "Walross - Pair of Walrus.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Stingray",
        "scientific_name": "Dasyatis pastinaca",
        "fun_fact": "Stingrays are closely related to sharks and can sense electrical signals from prey!",
        "image_file": "Dasyatis pastinaca, Genova.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Clown Triggerfish",
        "scientific_name": "Balistoides conspicillum",
        "fun_fact": "Clown triggerfish can lock their front spine upright to wedge into coral and sleep safely!",
        "image_file": "Balistoides conspicillum 2.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Blue Ringed Octopus",
        "scientific_name": "Hapalochlaena lunulata",
        "fun_fact": "Blue-ringed octopuses are tiny but carry enough venom to be one of the most dangerous sea creatures!",
        "image_file": "Hapalochlaena lunulata2.JPG",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Giant Clam",
        "scientific_name": "Tridacna gigas",
        "fun_fact": "Giant clams can weigh over 500 pounds and live for more than 100 years!",
        "image_file": "Tridacna gigas.001 - Aquarium Finisterrae.JPG",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Chambered Nautilus",
        "scientific_name": "Nautilus pompilius",
        "fun_fact": "Nautiluses have been around for over 500 million years — older than the dinosaurs!",
        "image_file": "Nautilus pompilius (head).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Flying Fish",
        "scientific_name": "Exocoetidae",
        "fun_fact": "Flying fish can glide through the air for over 600 feet to escape predators!",
        "image_file": "Flying fish.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Anglerfish",
        "scientific_name": "Lophius piscatorius",
        "fun_fact": "Anglerfish have a glowing lure on their head to attract prey in the deep dark ocean!",
        "image_file": "Lophius piscatorius MHNT.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Sand Dollar",
        "scientific_name": "Clypeaster reticulatus",
        "fun_fact": "Sand dollars are actually a type of sea urchin covered in tiny spines!",
        "image_file": "Sea cookie (Clypeaster reticulatus).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Sea Horse",
        "scientific_name": "Hippocampus abdominalis",
        "fun_fact": "Seahorses have no stomach — food passes through them so fast they need to eat almost constantly!",
        "image_file": "Big-belly seahorse (Hippocampus abdominalis).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Sperm Whale",
        "scientific_name": "Physeter macrocephalus",
        "fun_fact": "Sperm whales have the largest brain of any animal that has ever lived!",
        "image_file": "Mother and baby sperm whale.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 2.0",
    },
    {
        "common_name": "Coral",
        "scientific_name": "Acropora cervicornis",
        "fun_fact": "Coral reefs are built by tiny animals called polyps and can be thousands of years old!",
        "image_file": "Staghorn-coral-1.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Horseshoe Crab",
        "scientific_name": "Limulus polyphemus",
        "fun_fact": "Horseshoe crabs have blue blood and have existed for over 450 million years!",
        "image_file": "Horseshoe crab (Limulus polyphemus).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Dugong",
        "scientific_name": "Dugong dugon",
        "fun_fact": "Dugongs are the only marine mammals that are strictly herbivores!",
        "image_file": "Dugong Marsa Alam.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Sea Cucumber",
        "scientific_name": "Holothuria tubulosa",
        "fun_fact": "Sea cucumbers can eject their internal organs to confuse predators and then regrow them!",
        "image_file": "Holothuria tubulosa.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Spotted Eagle Ray",
        "scientific_name": "Aetobatus narinari",
        "fun_fact": "Spotted eagle rays can leap completely out of the water!",
        "image_file": "Spotted Eagle Ray (Aetobatus narinari)2.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Sea Lion",
        "scientific_name": "Zalophus californianus",
        "fun_fact": "Sea lions can rotate their back flippers to walk on land unlike seals!",
        "image_file": "Zalophus californianus -Pier 39, San Francisco, California, USA-8.jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Mandarin Fish",
        "scientific_name": "Synchiropus splendidus",
        "fun_fact": "Mandarin fish are one of the most colorful fish in the ocean!",
        "image_file": "Synchiropus splendidus 2 Luc Viatour.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Parrotfish",
        "scientific_name": "Scarus vetula",
        "fun_fact": "Parrotfish make sand by eating coral and pooping it out — one fish can make 800 pounds a year!",
        "image_file": "Queen Parrotfish (Scarus vetula).jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Wobbegong Shark",
        "scientific_name": "Orectolobus maculatus",
        "fun_fact": "Wobbegong sharks have tassels around their mouth that look like seaweed to hide on the ocean floor!",
        "image_file": "Spotted Wobbegong.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Sunfish",
        "scientific_name": "Mola mola",
        "fun_fact": "Ocean sunfish can weigh over 5,000 pounds and love to sunbathe at the surface!",
        "image_file": "Mola mola.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Barracuda",
        "scientific_name": "Sphyraena barracuda",
        "fun_fact": "Barracudas can swim in bursts up to 36 miles per hour!",
        "image_file": "Barracuda laban.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Frogfish",
        "scientific_name": "Antennarius maculatus",
        "fun_fact": "Frogfish have a built-in fishing rod on their head to lure prey!",
        "image_file": "Antennarius maculatus 1.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Garden Eel",
        "scientific_name": "Heteroconger hassi",
        "fun_fact": "Garden eels live in burrows and sway in the current like an underwater garden!",
        "image_file": "Spotted garden eels (Heteroconger hassi).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Mantis Shrimp",
        "scientific_name": "Odontodactylus scyllarus",
        "fun_fact": "Mantis shrimp can punch with the force of a bullet and see 16 types of color!",
        "image_file": "Odontodactylus scyllarus 2.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Christmas Tree Worm",
        "scientific_name": "Spirobranchus giganteus",
        "fun_fact": "Christmas tree worms come in many colors and look like tiny underwater Christmas trees!",
        "image_file": "Spirobranchus giganteus (Red and white christmas tree worm).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Sea Anemone",
        "scientific_name": "Actinia equina",
        "fun_fact": "Sea anemones look like flowers but are actually animals with stinging tentacles!",
        "image_file": "Actinia equina (Beadlet anemone).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "Boxer Crab",
        "scientific_name": "Lybia tessellata",
        "fun_fact": "Boxer crabs carry tiny anemones in their claws and wave them like pom-poms for defense!",
        "image_file": "Lybia tessellata (Boxer crab).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Crown-of-Thorns Starfish",
        "scientific_name": "Acanthaster planci",
        "fun_fact": "Crown-of-thorns starfish can have up to 21 arms covered in venomous spines!",
        "image_file": "Acanthaster planci - Koh Tao.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Goblin Shark",
        "scientific_name": "Mitsukurina owstoni",
        "fun_fact": "Goblin sharks can shoot their jaws forward to snatch prey like a slingshot!",
        "image_file": "Mistukurina owstoni museum victoria - head detail.jpg",
        "image_credit": "Wikimedia Commons, CC BY 3.0",
    },
    {
        "common_name": "Vampire Squid",
        "scientific_name": "Vampyroteuthis infernalis",
        "fun_fact": "Vampire squid live in the deep ocean and can turn inside out to protect themselves!",
        "image_file": "Vampyroteuthis infernalis.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 4.0",
    },
    {
        "common_name": "King Crab",
        "scientific_name": "Paralithodes camtschaticus",
        "fun_fact": "King crabs can have a leg span of up to 6 feet across!",
        "image_file": "Red king crab.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Cookiecutter Shark",
        "scientific_name": "Isistius brasiliensis",
        "fun_fact": "Cookiecutter sharks bite perfect round chunks out of larger animals like a cookie cutter!",
        "image_file": "Isistius brasiliensis.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Decorator Crab",
        "scientific_name": "Camposcia retusa",
        "fun_fact": "Decorator crabs glue bits of seaweed and sponge to their shells for camouflage!",
        "image_file": "Camposcia retusa.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Leafy Seadragon",
        "scientific_name": "Phycodurus eques",
        "fun_fact": "Leafy seadragons are so good at camouflage they look like floating pieces of kelp!",
        "image_file": "Leafy seadragon.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Carpet Shark",
        "scientific_name": "Orectolobus ornatus",
        "fun_fact": "Carpet sharks are masters of disguise, lying flat on the ocean floor waiting for prey!",
        "image_file": "Ornate wobbegong.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Giant Spider Crab",
        "scientific_name": "Macrocheira kaempferi",
        "fun_fact": "Giant spider crabs have the longest leg span of any arthropod — up to 12 feet!",
        "image_file": "Macrocheira kaempferi.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Chambered Nautilus",
        "scientific_name": "Nautilus pompilius",
        "fun_fact": "Nautiluses fill their shell chambers with gas to float up and liquid to sink down!",
        "image_file": "Nautilus pompilius.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Harbor Seal",
        "scientific_name": "Phoca vitulina",
        "fun_fact": "Harbor seals can sleep underwater and come up to breathe without even waking up!",
        "image_file": "Common Seal Phoca vitulina.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Pilot Whale",
        "scientific_name": "Globicephala melas",
        "fun_fact": "Pilot whales are actually large dolphins and live in tight family groups!",
        "image_file": "Globicephala melas 2.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Basking Shark",
        "scientific_name": "Cetorhinus maximus",
        "fun_fact": "Basking sharks are the second largest fish and swim with their mouths wide open to filter food!",
        "image_file": "Cetorhinus maximus by greg skomal.JPG",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Electric Eel",
        "scientific_name": "Electrophorus electricus",
        "fun_fact": "Electric eels can produce shocks of up to 860 volts — enough to stun a horse!",
        "image_file": "Electric-eel.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Longhorn Cowfish",
        "scientific_name": "Lactoria cornuta",
        "fun_fact": "Longhorn cowfish have two cute horns on their head and can release toxins when stressed!",
        "image_file": "Lactoria cornuta.002 - Aquarium Finisterrae.JPG",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Spinner Dolphin",
        "scientific_name": "Stenella longirostris",
        "fun_fact": "Spinner dolphins can spin up to seven times in a single leap out of the water!",
        "image_file": "Spinner Dolphin Off Kauai.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Blobfish",
        "scientific_name": "Psychrolutes marcidus",
        "fun_fact": "Blobfish look normal underwater — they only look blobby because of pressure changes at the surface!",
        "image_file": "Psychrolutes marcidus.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Mimic Octopus",
        "scientific_name": "Thaumoctopus mimicus",
        "fun_fact": "Mimic octopuses can imitate the shape and movement of over 15 different species!",
        "image_file": "Mimic Octopus 2.jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Sea Pen",
        "scientific_name": "Virgularia mirabilis",
        "fun_fact": "Sea pens are colonies of tiny animals that look like old-fashioned quill pens!",
        "image_file": "Virgularia mirabilis.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Coconut Octopus",
        "scientific_name": "Amphioctopus marginatus",
        "fun_fact": "Coconut octopuses carry coconut shells to use as portable shelters — one of few tool-using invertebrates!",
        "image_file": "Octopus marginatus, Bali, Indonesia (croped).jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Yellowfin Tuna",
        "scientific_name": "Thunnus albacares",
        "fun_fact": "Yellowfin tuna can swim at speeds of up to 50 miles per hour!",
        "image_file": "Yellowfin tuna nurp.jpg",
        "image_credit": "Wikimedia Commons, Public Domain",
    },
    {
        "common_name": "Cleaner Wrasse",
        "scientific_name": "Labroides dimidiatus",
        "fun_fact": "Cleaner wrasse set up cleaning stations where other fish line up to have parasites removed!",
        "image_file": "Bluestreak cleaner wrasse.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Box Jellyfish",
        "scientific_name": "Chironex fleckeri",
        "fun_fact": "Box jellyfish have 24 eyes but scientists are still figuring out how they process what they see!",
        "image_file": "Avispa marina croridge.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Lemon Shark",
        "scientific_name": "Negaprion brevirostris",
        "fun_fact": "Lemon sharks get their name from their yellowish skin that helps them blend into sandy ocean floors!",
        "image_file": "Lemon shark.jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Sea Urchin",
        "scientific_name": "Diadema setosum",
        "fun_fact": "Sea urchins walk on tiny tube feet hidden among their spines!",
        "image_file": "Diadema setosum.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Ribbon Eel",
        "scientific_name": "Rhinomuraena quaesita",
        "fun_fact": "Ribbon eels change from black to blue to yellow as they grow up!",
        "image_file": "Rhinomuraena quaesita.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
    {
        "common_name": "Pygmy Seahorse",
        "scientific_name": "Hippocampus bargibanti",
        "fun_fact": "Pygmy seahorses are so tiny and well-camouflaged they were only discovered by accident!",
        "image_file": "Hippocampus bargibanti, Muricella sp. (Sea fan).jpg",
        "image_credit": "Wikimedia Commons, CC BY 2.0",
    },
    {
        "common_name": "Weedy Seadragon",
        "scientific_name": "Phyllopteryx taeniolatus",
        "fun_fact": "Male weedy seadragons carry the eggs under their tail until they hatch!",
        "image_file": "Phyllopteryx taeniolatus 1.jpg",
        "image_credit": "Wikimedia Commons, CC BY-SA 3.0",
    },
]
